# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e3a5dace86532c9dd269961a0554d3b1f38ac362f2a4c3118c567f5b667c40b423505722c6ecfd57bc986f8127c2c415956af59adc1a0c3c38117f9a1039e11

test:
  secret_key_base: 48ccab7f101bf3b19c80bfc61690750fe64716766a79c0e09079490a55d23709ca3a730661b5ede2f3f78af39cce3b160dd18f9bfb38d521f3d37ee5e1fd09a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
